List<Map<String, dynamic>> products = [
  {
    "id": 1,
    "typeID": 2,
    "name": "Shirt",
    "desc": "girls shirt with floral design",
    "price": 1200,
    "image": "assets/images/shirt1.jpg",
  },
  {
    "id": 2,
    "typeID": 3,
    "name": "pants",
    "desc": "wide Leg pants with side stripes",
    "price": 950,
    "image": "assets/images/pans1.jpg",
  },
  {
    "id": 3,
    "typeID": 1,
    "name": "Jacket",
    "desc": "Black jacket for mens with zipper details",
    "price": 1250,
    "image": "assets/images/jacket1.jpg",
  },
  {
    "id": 4,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Cotton shirt with checkered pattern",
    "price": 1100,
    "image": "assets/images/shirt2.jpg",
  },
  {
    "id": 5,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Casual shirt",
    "price": 850,
    "image": "assets/images/image5.jpeg",
  },
  {
    "id": 6,
    "typeID": 1,
    "name": "Jacket",
    "desc": "Denim jacket with distressed look",
    "price": 1150,
    "image": "assets/images/jacket2.jpg",
  },
  {
    "id": 7,
    "typeID": 3,
    "name": "pants",
    "desc": "Slim-fit trousers",
    "price": 1000,
    "image": "assets/images/pans2.jpg",
  },
  {
    "id": 8,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Striped shirt",
    "price": 950,
    "image": "assets/images/shirt3.jpg",
  },
  {
    "id": 9,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Cotton shirt",
    "price": 1200,
    "image": "assets/images/shirt4.jpg",
  },
  {
    "id": 10,
    "typeID": 3,
    "name": "pants",
    "desc": "Cargo pants with multiple pockets",
    "price": 1150,
    "image": "assets/images/pans3.jpg",
  },
  {
    "id": 11,
    "typeID": 3,
    "name": "pants",
    "desc": "Skinny jeans",
    "price": 1000,
    "image": "assets/images/pans4.jpg",
  },
  {
    "id": 12,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Floral print shirt",
    "price": 1200,
    "image": "assets/images/shirt5.jpg",
  },
  {
    "id": 13,
    "typeID": 5,
    "name": "Boot",
    "desc": "Leather boots",
    "price": 1250,
    "image": "assets/images/shoes1.jpg",
  },
  {
    "id": 14,
    "typeID": 3,
    "name": "pants",
    "desc": "Chinos",
    "price": 900,
    "image": "assets/images/pans5.jpg",
  },
  {
    "id": 15,
    "typeID": 2,
    "name": "Shirt",
    "desc": "V-neck t-shirt",
    "price": 850,
    "image": "assets/images/shirt6.jpg",
  },
  {
    "id": 16,
    "typeID": 3,
    "name": "pants",
    "desc": "Cropped trousers",
    "price": 1100,
    "image": "assets/images/pans6.jpg",
  },
  {
    "id": 17,
    "typeID": 1,
    "name": "Jacket",
    "desc": "Hooded jacket",
    "price": 1280,
    "image": "assets/images/jacket3.jpg",
  },
  {
    "id": 18,
    "typeID": 3,
    "name": "pants",
    "desc": "Sweatpants",
    "price": 920,
    "image": "assets/images/pans7.jpg",
  },
  {
    "id": 19,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Long-sleeve shirt",
    "price": 800,
    "image": "assets/images/shirt7.jpg",
  },
  {
    "id": 20,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Denim shirt",
    "price": 1150,
    "image": "assets/images/shirt8.jpg",
  },
  {
    "id": 21,
    "typeID": 5,
    "name": "Boot",
    "desc": "Suede ankle boots",
    "price": 1250,
    "image": "assets/images/shoes2.jpg",
  },
  {
    "id": 22,
    "typeID": 5,
    "name": "Boot",
    "desc": "Leather boots",
    "price": 1200,
    "image": "assets/images/shoes3.jpg",
  },
  {
    "id": 23,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Button-up shirt",
    "price": 950,
    "image": "assets/images/shirt9.jpg",
  },
  {
    "id": 24,
    "typeID": 4,
    "name": "Bag",
    "desc": "Canvas tote bag",
    "price": 800,
    "image": "assets/images/bag1.jpg",
  },
  {
    "id": 25,
    "typeID": 1,
    "name": "Jacket",
    "desc": "Puffer jacket",
    "price": 1200,
    "image": "assets/images/jacket4.jpg",
  },
  {
    "id": 26,
    "typeID": 4,
    "name": "Bag",
    "desc": "Leather shoulder bag",
    "price": 950,
    "image": "assets/images/bag2.png",
  },
  {
    "id": 27,
    "typeID": 1,
    "name": "Jacket",
    "desc": "Bomber jacket",
    "price": 1200,
    "image": "assets/images/jacket5.jpeg",
  },
  {
    "id": 28,
    "typeID": 4,
    "name": "Bag",
    "desc": "Crossbody bag",
    "price": 780,
    "image": "assets/images/bag3.jpeg",
  },
  {
    "id": 29,
    "typeID": 4,
    "name": "Bag",
    "desc": "Nylon backpack",
    "price": 950,
    "image": "assets/images/bag4.jpeg",
  },
];

List catlist = [
  "All",
  "jackets",
  "shirts",
  "pants",
  "Bags",
];


List<Map<String, dynamic>> bags = [
  {
    "id": 24,
    "typeID": 4,
    "name": "Bag",
    "desc": "Canvas tote bag",
    "price": 800,
    "image": "assets/images/bag1.jpg",
  },
  {
    "id": 26,
    "typeID": 4,
    "name": "Bag",
    "desc": "Leather shoulder bag",
    "price": 950,
    "image": "assets/images/bag2.png",
  },
  {
    "id": 28,
    "typeID": 4,
    "name": "Bag",
    "desc": "Crossbody bag",
    "price": 780,
    "image": "assets/images/bag3.jpeg",
  },
  {
    "id": 29,
    "typeID": 4,
    "name": "Bag",
    "desc": "Nylon backpack",
    "price": 950,
    "image": "assets/images/bag4.jpeg",
  },
];

List<Map<String, dynamic>> jackets = [
  {
    "id": 3,
    "typeID": 1,
    "name": "Jacket",
    "desc": "Black jacket for mens with zipper details",
    "price": 1250,
    "image": "assets/images/jacket1.jpg",
  },
  {
    "id": 6,
    "typeID": 1,
    "name": "Jacket",
    "desc": "Denim jacket with distressed look",
    "price": 1150,
    "image": "assets/images/jacket2.jpg",
  },
  {
    "id": 17,
    "typeID": 1,
    "name": "Jacket",
    "desc": "Hooded jacket",
    "price": 1280,
    "image": "assets/images/jacket3.jpg",
  },
  {
    "id": 25,
    "typeID": 1,
    "name": "Jacket",
    "desc": "Puffer jacket",
    "price": 1200,
    "image": "assets/images/jacket4.jpg",
  },
  {
    "id": 27,
    "typeID": 1,
    "name": "Jacket",
    "desc": "Bomber jacket",
    "price": 1200,
    "image": "assets/images/jacket5.jpeg",
  },
];


List<Map<String, dynamic>> pants = [
  {
    "id": 2,
    "typeID": 3,
    "name": "pants",
    "desc": "wide Leg pants with side stripes",
    "price": 950,
    "image": "assets/images/pans1.jpg",
  },
  {
    "id": 7,
    "typeID": 3,
    "name": "pants",
    "desc": "Slim-fit trousers",
    "price": 1000,
    "image": "assets/images/pans2.jpg",
  },
  {
    "id": 10,
    "typeID": 3,
    "name": "pants",
    "desc": "Cargo pants with multiple pockets",
    "price": 1150,
    "image": "assets/images/pans3.jpg",
  },
  {
    "id": 11,
    "typeID": 3,
    "name": "pants",
    "desc": "Skinny jeans",
    "price": 1000,
    "image": "assets/images/pans4.jpg",
  },
  {
    "id": 14,
    "typeID": 3,
    "name": "pants",
    "desc": "Chinos",
    "price": 900,
    "image": "assets/images/pans5.jpg",
  },
  {
    "id": 16,
    "typeID": 3,
    "name": "pants",
    "desc": "Cropped trousers",
    "price": 1100,
    "image": "assets/images/pans6.jpg",
  },
  {
    "id": 18,
    "typeID": 3,
    "name": "pants",
    "desc": "Sweatpants",
    "price": 920,
    "image": "assets/images/pans7.jpg",
  },
];

List<Map<String, dynamic>> shirts = [
{
  "id": 1,
  "typeID": 2,
  "name": "Shirt",
  "desc": "girls shirt with floral design",
  "price": 1200,
  "image": "assets/images/shirt1.jpg",
},
  {
    "id": 4,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Cotton shirt with checkered pattern",
    "price": 1100,
    "image": "assets/images/shirt2.jpg",
  },
  {
    "id": 5,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Casual shirt",
    "price": 850,
    "image": "assets/images/image5.jpeg",
  },
  {
    "id": 8,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Striped shirt",
    "price": 950,
    "image": "assets/images/shirt3.jpg",
},
{
  "id": 9,
  "typeID": 2,
  "name": "Shirt",
  "desc": "Cotton shirt",
  "price": 1200,
  "image": "assets/images/shirt4.jpg",
},
{
  "id": 12,
  "typeID": 2,
  "name": "Shirt",
  "desc": "Floral print shirt",
  "price": 1200,
  "image": "assets/images/shirt5.jpg",
},
{
  "id": 15,
  "typeID": 2,
  "name": "Shirt",
  "desc": "V-neck t-shirt",
  "price": 850,
  "image": "assets/images/shirt6.jpg",
},
{
  "id": 19,
  "typeID": 2,
  "name": "Shirt",
  "desc": "Long-sleeve shirt",
  "price": 800,
  "image": "assets/images/shirt7.jpg",
},
{
  "id": 20,
  "typeID": 2,
  "name": "Shirt",
  "desc": "Denim shirt",
  "price": 1150,
  "image": "assets/images/shirt8.jpg",
},
  {
    "id": 23,
    "typeID": 2,
    "name": "Shirt",
    "desc": "Button-up shirt",
    "price": 950,
    "image": "assets/images/shirt9.jpg",
  },


];
